# Generated by Django 4.2.2 on 2023-07-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('phoneNo', models.CharField(max_length=10)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('userId', models.AutoField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
    ]
